import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlin: String = "1.3.72"

    const val androidx_lifecycle: String = "2.3.0-alpha03"

    const val androidx_fragment: String = "1.3.0-alpha05"

    const val androidx_test: String = "1.2.0"

    const val com_android_tools_build_gradle: String = "4.0.0"

    const val org_jlleitschuh_gradle_ktlint_gradle_plugin: String = "9.2.1"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val com_jfrog_bintray_gradle_plugin: String = "1.8.5"

    const val coroutines_test_extensions: String = "0.1.2"

    const val espresso_core: String = "3.2.0"

    const val lint_gradle: String = "27.0.0"

    const val appcompat: String = "1.1.0"

    const val junit_ktx: String = "1.1.1"

    const val ktlint: String = "0.36.0"

    const val aapt2: String = "4.0.0-6051327"

    /**
     * Current version: "6.4.1"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.4.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
