import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.3.9"

    const val androidx_lifecycle: String = "2.3.0-alpha07"

    const val androidx_test: String = "1.3.0"

    const val com_android_tools_build_gradle: String = "4.0.1"

    const val org_jlleitschuh_gradle_ktlint_gradle_plugin: String = "9.2.1" // available: "9.4.0"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val com_jfrog_bintray_gradle_plugin: String = "1.8.5"

    const val binary_compatibility_validator: String = "0.2.3"

    const val coroutines_test_extensions: String = "0.1.2"

    const val kotlin_gradle_plugin: String = "1.4.10"

    const val fragment_testing: String = "1.2.5"

    const val espresso_core: String = "3.3.0"

    const val lint_gradle: String = "27.0.1"

    const val appcompat: String = "1.3.0-alpha02"

    const val junit_ktx: String = "1.1.2"

    const val ktlint: String = "0.36.0" // available: "0.38.1"

    const val aapt2: String = "4.0.1-6197926"

    /**
     * Current version: "6.6.1"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.6.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
        id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
