name: deploy

on:
  push:
    tags:
      - '*'

jobs:
  all_checks:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - name: "Set up Java"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: "Checks all the things"
        run: ./gradlew lint ktlintCheck apiCheck assemble

  publish:
    needs: [all_checks]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - name: "Set up Java"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: "Get tag and save into env"
        uses: olegtarasov/get-tag@v1
        id: tagName
      - name: "Build, publish and upload to Bintray"
        env:
          libraryVersionTag: ${{ steps.tagName.outputs.tag }}
          bintrayUser: ${{ secrets.BINTRAY_USER }}
          bintrayApiKey: ${{ secrets.BINTRAY_TOKEN }}
        run: ./gradlew build publish bintrayUpload